import type { Obra } from "./types";
import {
  PAREDES_INTERNO_INICIAL,
  labelParedeInterno,
} from "./paredes-interno";
import { PAREDES_DRYWALL_INICIAL, labelParede } from "./paredes-drywall";
import {
  APONTAMENTOS_PORCELANATO_INICIAL,
  TIPOS_PORCELANATO_INICIAL,
  labelPorcelanatoCurto,
} from "./porcelanato";
import { FORRO_INICIAL } from "./forro";

export const OBRA_DATA_VERSION = 14;

export const OBRA_SICREDI: Obra = {
  id: "sicredi-001",
  nome: "Sicredi - Steel Frame",
  cliente: "Sicredi",
  dataInicio: "2026-06-10",
  escopo: [
    { localizacao: "Frontal", areaTotalM2: 201 },
    { localizacao: "Lateral Direita", areaTotalM2: 102 },
    { localizacao: "Fundos", areaTotalM2: 212 },
    { localizacao: "Lateral Esquerda", areaTotalM2: 133 },
    { localizacao: "Platibanda", areaTotalM2: 117 },
    { localizacao: "Volume Caixa D'água", areaTotalM2: 39 },
    { localizacao: "Coroamento da Platibanda", areaTotalM2: 96 },
    { localizacao: "Laje Inferior Frontal", areaTotalM2: 31.42 },
  ],
  paredesDrywall: PAREDES_DRYWALL_INICIAL,
  paredesInterno: PAREDES_INTERNO_INICIAL,
  tiposPorcelanato: TIPOS_PORCELANATO_INICIAL,
  apontamentosPorcelanato: APONTAMENTOS_PORCELANATO_INICIAL,
  forro: FORRO_INICIAL,
  observacoesGerais:
    "Dados sincronizados com a planilha Produtividade Sicredi (01/08/2026).",
  registros: [
    {
      id: "r1",
      equipe: "William e Julio",
      localizacao: "Fundos",
      data: "2026-06-10",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 54.72,
    },
    {
      id: "r2",
      equipe: "William e Julio",
      localizacao: "Fundos",
      data: "2026-06-11",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 95.04,
    },
    {
      id: "r3",
      equipe: "William e Julio",
      localizacao: "Fundos",
      data: "2026-06-12",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 62.24,
    },
    {
      id: "r4",
      equipe: "William e Julio",
      localizacao: "Fundos",
      data: "2026-06-14",
      servico: "Tratamento de Juntas",
      areaM2: 212,
    },
    {
      id: "r5",
      equipe: "William e Julio",
      localizacao: "Fundos",
      data: "2026-06-15",
      servico: "Basecoat",
      areaM2: 48.96,
    },
    {
      id: "r6",
      equipe: "William e Julio",
      localizacao: "Fundos",
      data: "2026-06-16",
      servico: "Basecoat",
      areaM2: 57.6,
    },
    {
      id: "r7",
      equipe: "William",
      localizacao: "Fundos",
      data: "2026-07-16",
      servico: "Basecoat",
      areaM2: 52.72,
    },
    {
      id: "r8",
      equipe: "William",
      localizacao: "Fundos",
      data: "2026-07-17",
      servico: "Basecoat",
      areaM2: 52.72,
    },
    {
      id: "r9",
      equipe: "William e Julio",
      localizacao: "Lateral Direita",
      data: "2026-06-17",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 20.16,
    },
    {
      id: "r10",
      equipe: "William e Julio",
      localizacao: "Lateral Direita",
      data: "2026-06-18",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 24,
    },
    {
      id: "r11",
      equipe: "William e Julio",
      localizacao: "Lateral Direita",
      data: "2026-06-19",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 25.92,
    },
    {
      id: "r12",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-22",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 17,
    },
    {
      id: "r13",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-26",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 14.92,
    },
    {
      id: "r14",
      equipe: "William e Julio",
      localizacao: "Lateral Direita",
      data: "2026-06-20",
      servico: "Tratamento de Juntas",
      areaM2: 70.08,
    },
    {
      id: "r15",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-26",
      servico: "Tratamento de Juntas",
      areaM2: 31.92,
    },
    {
      id: "r16",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-22",
      servico: "Basecoat",
      areaM2: 29.7,
    },
    {
      id: "r17",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-24",
      servico: "Basecoat",
      areaM2: 42,
    },
    {
      id: "r18",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-26",
      servico: "Basecoat",
      areaM2: 18.3,
    },
    {
      id: "r19",
      equipe: "William e Venancio",
      localizacao: "Lateral Direita",
      data: "2026-06-27",
      servico: "Basecoat",
      areaM2: 12,
    },
    {
      id: "r20",
      equipe: "Walter",
      localizacao: "Lateral Direita",
      data: "2026-06-30",
      servico: "Basecoat",
      areaM2: 18.3,
    },
    {
      id: "r21",
      equipe: "Alex e Venancio",
      localizacao: "Lateral esquerda",
      data: "2026-06-11",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 60.48,
    },
    {
      id: "r22",
      equipe: "Alex e Venancio",
      localizacao: "Lateral esquerda",
      data: "2026-06-12",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 25.98,
    },
    {
      id: "r23",
      equipe: "Alex e Venancio",
      localizacao: "Lateral esquerda",
      data: "2026-06-13",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 31.3,
    },
    {
      id: "r24",
      equipe: "Alex e Venancio",
      localizacao: "Lateral esquerda",
      data: "2026-06-14",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 15.24,
    },
    {
      id: "r25",
      equipe: "Carlos e Alex",
      localizacao: "Lateral esquerda",
      data: "2026-07-10",
      servico: "Tratamento de Juntas",
      areaM2: 25.46,
    },
    {
      id: "r26",
      equipe: "William",
      localizacao: "Lateral esquerda",
      data: "2026-07-14",
      servico: "Tratamento de Juntas",
      areaM2: 36,
    },
    {
      id: "r27",
      equipe: "William",
      localizacao: "Lateral esquerda",
      data: "2026-07-15",
      servico: "Tratamento de Juntas",
      areaM2: 25.51,
    },
    {
      id: "r28",
      equipe: "William e Kauan",
      localizacao: "Lateral esquerda",
      data: "2026-07-22",
      servico: "Tratamento de Juntas",
      areaM2: 23.015,
    },
    {
      id: "r29",
      equipe: "William e Kauan",
      localizacao: "Lateral esquerda",
      data: "2026-07-23",
      servico: "Tratamento de Juntas",
      areaM2: 23.015,
    },
    {
      id: "r30",
      equipe: "Carlos e Alex",
      localizacao: "Lateral esquerda",
      data: "2026-07-10",
      servico: "Basecoat",
      areaM2: 25.46,
    },
    {
      id: "r31",
      equipe: "William",
      localizacao: "Lateral esquerda",
      data: "2026-07-14",
      servico: "Basecoat",
      areaM2: 36,
    },
    {
      id: "r32",
      equipe: "William",
      localizacao: "Lateral esquerda",
      data: "2026-07-15",
      servico: "Basecoat",
      areaM2: 25.51,
    },
    {
      id: "r33",
      equipe: "William e Kauan",
      localizacao: "Lateral esquerda",
      data: "2026-07-22",
      servico: "Basecoat",
      areaM2: 23.015,
    },
    {
      id: "r34",
      equipe: "William e Kauan",
      localizacao: "Lateral esquerda",
      data: "2026-07-23",
      servico: "Basecoat",
      areaM2: 23.015,
    },
    {
      id: "r35",
      equipe: "Alex e Venancio",
      localizacao: "Fachada Frontal",
      data: "2026-06-14",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 15.84,
    },
    {
      id: "r36",
      equipe: "Alex e Venancio",
      localizacao: "Fachada Frontal",
      data: "2026-06-15",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 17.28,
    },
    {
      id: "r37",
      equipe: "Alex e Venancio",
      localizacao: "Fachada Frontal",
      data: "2026-06-16",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 24.48,
    },
    {
      id: "r38",
      equipe: "Alex e Venancio",
      localizacao: "Fachada Frontal",
      data: "2026-06-17",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 15.84,
    },
    {
      id: "r39",
      equipe: "Alex e Venancio",
      localizacao: "Fachada Frontal",
      data: "2026-06-18",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 9.6,
    },
    {
      id: "r40",
      equipe: "Alex e Venancio",
      localizacao: "Fachada Frontal",
      data: "2026-06-19",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 17.28,
    },
    {
      id: "r41",
      equipe: "Rafael e Venâncio",
      localizacao: "Fachada Frontal",
      data: "2026-06-23",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 13.44,
    },
    {
      id: "r42",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-24",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 13.44,
    },
    {
      id: "r43",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-25",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 25,
    },
    {
      id: "r44",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-29",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 34,
    },
    {
      id: "r45",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-30",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 8,
    },
    {
      id: "r46",
      equipe: "Fabio e Alessandro",
      localizacao: "Fachada Frontal",
      data: "2026-07-03",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 6.8,
    },
    {
      id: "r47",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-24",
      servico: "Tratamento de Juntas",
      areaM2: 22.1,
    },
    {
      id: "r48",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-26",
      servico: "Tratamento de Juntas",
      areaM2: 130.1,
    },
    {
      id: "r49",
      equipe: "William",
      localizacao: "Fachada Frontal",
      data: "2026-07-06",
      servico: "Tratamento de Juntas",
      areaM2: 24.4,
    },
    {
      id: "r50",
      equipe: "William",
      localizacao: "Fachada Frontal",
      data: "2026-07-07",
      servico: "Tratamento de Juntas",
      areaM2: 24.4,
    },
    {
      id: "r51",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-24",
      servico: "Basecoat",
      areaM2: 22.1,
    },
    {
      id: "r52",
      equipe: "Walter e Carlos",
      localizacao: "Fachada Frontal",
      data: "2026-06-26",
      servico: "Basecoat",
      areaM2: 130.1,
    },
    {
      id: "r53",
      equipe: "William",
      localizacao: "Fachada Frontal",
      data: "2026-07-06",
      servico: "Basecoat",
      areaM2: 24.4,
    },
    {
      id: "r54",
      equipe: "William",
      localizacao: "Fachada Frontal",
      data: "2026-07-07",
      servico: "Basecoat",
      areaM2: 24.4,
    },
    {
      id: "r55",
      equipe: "Fabio e Alessandro",
      localizacao: "Laje Inferior Frontal",
      data: "2026-06-27",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 15.58,
    },
    {
      id: "r56",
      equipe: "Fabio e Alessandro",
      localizacao: "Laje Inferior Frontal",
      data: "2026-06-28",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 15.84,
    },
    {
      id: "r57",
      equipe: "Fabio e Alessandro",
      localizacao: "Laje Inferior Frontal",
      data: "2026-06-27",
      servico: "Tratamento de Juntas",
      areaM2: 15.58,
    },
    {
      id: "r58",
      equipe: "Fabio e Alessandro",
      localizacao: "Laje Inferior Frontal",
      data: "2026-06-28",
      servico: "Tratamento de Juntas",
      areaM2: 15.84,
    },
    {
      id: "r59",
      equipe: "Fabio e Alessandro",
      localizacao: "Laje Inferior Frontal",
      data: "2026-06-27",
      servico: "Basecoat",
      areaM2: 15.58,
    },
    {
      id: "r60",
      equipe: "Fabio e Alessandro",
      localizacao: "Laje Inferior Frontal",
      data: "2026-06-28",
      servico: "Basecoat",
      areaM2: 15.84,
    },
    {
      id: "r61",
      equipe: "Pedro,Kauan e Alessandro",
      localizacao: "Volume Caixa D'água",
      data: "2026-06-26",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 39,
    },
    {
      id: "r62",
      equipe: "William e Venancio",
      localizacao: "Volume Caixa D'água",
      data: "2026-07-02",
      servico: "Tratamento de Juntas",
      areaM2: 39,
    },
    {
      id: "r63",
      equipe: "William e Venancio",
      localizacao: "Volume Caixa D'água",
      data: "2026-07-02",
      servico: "Basecoat",
      areaM2: 39,
    },
    {
      id: "r64",
      equipe: "Pedro e Kauan",
      localizacao: "Platibanda",
      data: "2026-06-26",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 35.1,
    },
    {
      id: "r65",
      equipe: "Pedro e Kauan",
      localizacao: "Platibanda",
      data: "2026-06-27",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 35.1,
    },
    {
      id: "r66",
      equipe: "William e Venancio",
      localizacao: "Platibanda",
      data: "2026-06-29",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 46.8,
    },
    {
      id: "r67",
      equipe: "William e Venancio",
      localizacao: "Platibanda",
      data: "2026-06-30",
      servico: "Tratamento de Juntas",
      areaM2: 117,
    },
    {
      id: "r68",
      equipe: "William e Venancio",
      localizacao: "Platibanda",
      data: "2026-07-01",
      servico: "Basecoat",
      areaM2: 87.75,
    },
    {
      id: "r69",
      equipe: "William e Venancio",
      localizacao: "Platibanda",
      data: "2026-07-02",
      servico: "Basecoat",
      areaM2: 29.25,
    },
    {
      id: "r70",
      equipe: "William e Venancio",
      localizacao: "Coroamento Platibanda",
      data: "2026-06-29",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 25,
    },
    {
      id: "r71",
      equipe: "William e Venancio",
      localizacao: "Coroamento Platibanda",
      data: "2026-06-30",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 40,
    },
    {
      id: "r72",
      equipe: "William e Venancio",
      localizacao: "Coroamento Platibanda",
      data: "2026-07-03",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 25,
    },
    {
      id: "r73",
      equipe: "William",
      localizacao: "Coroamento Platibanda",
      data: "2026-07-09",
      servico: "Plaqueamento Glasroc-x",
      areaM2: 6,
    },
    {
      id: "r74",
      equipe: "William e Venancio",
      localizacao: "Coroamento Platibanda",
      data: "2026-06-30",
      servico: "Tratamento de Juntas",
      areaM2: 40,
    },
    {
      id: "r75",
      equipe: "William",
      localizacao: "Coroamento Platibanda",
      data: "2026-07-08",
      servico: "Tratamento de Juntas",
      areaM2: 20,
    },
    {
      id: "r76",
      equipe: "William",
      localizacao: "Coroamento Platibanda",
      data: "2026-07-09",
      servico: "Tratamento de Juntas",
      areaM2: 36,
    },
    {
      id: "r77",
      equipe: "William",
      localizacao: "Coroamento Platibanda",
      data: "2026-07-08",
      servico: "Basecoat",
      areaM2: 40,
    },
    {
      id: "r78",
      equipe: "William",
      localizacao: "Coroamento Platibanda",
      data: "2026-07-09",
      servico: "Basecoat",
      areaM2: 56,
    },
    ...PAREDES_DRYWALL_INICIAL.filter((p) => p.dataExecucao).map((p) => ({
      id: `rd-${p.codigo}`,
      equipe: "Equipe Painéis Drywall",
      localizacao: labelParede(p.codigo),
      data: p.dataExecucao!,
      servico: "Paredes de Drywall" as const,
      areaM2: p.areaM2!,
      observacao: "Executado — aba Parede Drywall",
    })),
    ...PAREDES_INTERNO_INICIAL.flatMap((p) => {
      if (!p.dataExecucao) return [];
      const loc = labelParedeInterno(p);
      const regs = [];
      if (p.performaM2) {
        regs.push({
          id: `ri-perf-${p.id}`,
          equipe: "Equipe Plaqueamento Interno",
          localizacao: loc,
          data: p.dataExecucao,
          servico: "Plaqueamento Performa" as const,
          areaM2: p.performaM2,
          observacao: "Executado — aba Plaqueamento Interno",
        });
      }
      if (p.ruM2) {
        regs.push({
          id: `ri-ru-${p.id}`,
          equipe: "Equipe Plaqueamento Interno",
          localizacao: loc,
          data: p.dataExecucao,
          servico: "Plaqueamento RU" as const,
          areaM2: p.ruM2,
          observacao: "Executado — aba Plaqueamento Interno",
        });
      }
      return regs;
    }),
    ...APONTAMENTOS_PORCELANATO_INICIAL.map((a) => {
      const tipo = TIPOS_PORCELANATO_INICIAL.find((t) => t.id === a.tipoId)!;
      return {
        id: `rp-${a.id}`,
        equipe: "Equipe Porcelanato",
        localizacao: labelPorcelanatoCurto(tipo.descricao),
        data: a.dataExecucao,
        servico: "Assentamento de Porcelanato" as const,
        areaM2: a.areaExecutadaM2,
        observacao: "Executado — aba Porcelanato",
      };
    }),
    ...FORRO_INICIAL.filter((f) => f.dataPlaqueamento).map((f) => ({
      id: `rf-${f.id}`,
      equipe: "Equipe Forro",
      localizacao: f.ambiente,
      data: f.dataPlaqueamento!,
      servico: "Forro" as const,
      areaM2: f.areaM2,
      observacao: "Executado — aba Forro (plaqueamento)",
    })),
  ],
  resumos: [

  ],
};
